config/routes.rb
Rails.application.routes.draw do
  root "chatrooms#index"
  resources :chatrooms, only: [:index, :new, :create, :show] do
    resource :chatroom_memberships, only: [:create, :destroy] do
      post :accept
    end
    resources :messages, only: [:create]
  end
  devise_for :users, controllers: { sessions: "sessions", registrations: "registrations" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :chatroom_memberships, dependent: :destroy
  has_many :users, through: :chatroom_memberships
  has_many :messages

  validates :name, presence: true, uniqueness: true

  scope :public_channel,  -> { where(private_channel: false) }
  scope :private_channel, -> { where(private_channel: true) }
end

app/models/chatroom_membership.rb
class ChatroomMembership < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  before_create :set_last_read_at

  scope :active, -> { where(state: "accepted") }
  scope :pending, -> { where(state: "pending") }

  def accept_membership
    update(state: "accepted")
  end

  private

  def set_last_read_at
    self.last_read_at = Time.zone.now
  end
end

app/models/chatroom_user.rb
class ChatroomUser < ApplicationRecord
  belongs_to :chatroom
  belongs_to :user

  before_create :set_last_read_at

  private

  def set_last_read_at
    self.last_read_at = Time.zone.now
  end
end

app/models/message.rb
class Message < ApplicationRecord
  require "obscenity/active_model"

  belongs_to :chatroom
  belongs_to :user

  validates_presence_of :body, :chatroom, :user
  validates :body, obscenity: { sanitize: true }, if: :public_message?

  private

  def public_message?
    if chatroom.present?
      !chatroom.private_channel
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :chatroom_memberships, -> { active }, dependent: :destroy
  has_many :chatroom_invitations, -> { pending },
           class_name: "ChatroomMembership", dependent: :destroy
  has_many :chatrooms, through: :chatroom_memberships
  has_many :invited_chatrooms, through: :chatroom_invitations,
                               source: :chatroom
  has_many :messages

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  include Pundit

  protected

  def after_sign_in_path_for(_resource)
    chatrooms_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/chatroom_memberships_controller.rb
class ChatroomMembershipsController < ApplicationController
  def create
    @chatroom_membership = chatroom.chatroom_memberships.
                           find_or_create_by(user_id: current_user.id, state: "accepted")
    redirect_to chatroom
  end

  def accept
    @chatroom_membership = chatroom.chatroom_memberships.
                           find_or_create_by(user_id: current_user.id).accept_membership
    redirect_to chatroom
  end

  def destroy
    chatroom.chatroom_memberships.where(user_id: current_user.id).destroy_all
    redirect_to chatrooms_path
  end

  private

  def chatroom
    @chatroom ||= Chatroom.friendly.find(params[:chatroom_id])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  after_action :authorize_chatroom, only: [:new, :create, :show]

  def index
    @public_chatrooms = Chatroom.public_channel.order(name: :asc)
    authorize @public_chatrooms
  end

  def new
    @chatroom = Chatroom.new
    @users = User.all.without(current_user)
  end

  def create
    @chatroom = Chatroom.new(chatroom_params)

    if @chatroom.valid?
      @chatroom.save!
      add_current_user_to_chatroom(@chatroom)
      flash.notice = "Chatrooms created."
      redirect_to chatrooms_path
    else
      redirect_to new_chatroom_path
    end
  end

  def show
    @chatroom_membership = current_user.chatroom_memberships.find_by(chatroom_id: chatroom.id)
    @message = Message.new
    @messages = chatroom.messages.includes(:user).order(created_at: :desc).
                limit(100).reverse
    @unread_messages = false
  end

  private

  def chatroom
    @chatroom ||= Chatroom.friendly.find(params[:id])
  end

  def chatroom_params
    params.require(:chatroom).permit(:name, :private_channel, user_ids: [])
  end

  def authorize_chatroom
    authorize @chatroom
  end

  def add_current_user_to_chatroom(chatroom)
    ChatroomMembership.create(chatroom: chatroom, user: current_user).accept_membership
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  def new
    redirect_to new_user_session_path anchor: "tab-register"
  end

  def create
    super
    cookies[:action_cable_id] = resource.id
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  def create
    super
    cookies[:action_cable_id] = current_user.id
  end

  def destroy
    cookies[:action_cable_id] = "signed out"
    super
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def join_or_leave_link(user, chatroom)
    if user.chatrooms.include?(chatroom)
      link_to chatroom_chatroom_memberships_path(chatroom), method: :delete do
        content_tag(:i, "", class: "icon-line-cross", style: "color: #00CDCD")
      end
    else
      link_to chatroom_chatroom_memberships_path(chatroom), method: :post do
        content_tag(:i, "", class: "icon-plus", style: "color: #00CDCD")
      end
    end
  end
end

app/views/chatrooms/index.html.haml
%section#content
  .content-wrap
    .container.clearfix
      .heading-block.center.nobottomborder
        = image_tag "slogan.svg"
      .col_one_third.topmargin
      .col_one_third.topmargin
        .feature-box.fbox-center.fbox-light.fbox-plain
          .fbox-icon
            %i.icon-comments-alt
          %h3 Chatrooms
          %ul.nobottommargin
            - @public_chatrooms.each do |chatroom|
              %li{style: "list-style-type: none;"}
                = chatroom.name
                = join_or_leave_link(current_user, chatroom)
      .col_one_third.col_last.topmargin
        .feature-box.fbox-center.fbox-light.fbox-plain
          = link_to new_chatroom_path do
            .fbox-icon
              %i.icon-plus
            %h3 Start a New Chat

app/views/chatrooms/new.html.haml
%section#content
  .content-wrap
    .container.clearfix
      .panel.panel-default.nobottommargin
        .panel-body{style: "padding: 40px;"}
          = simple_form_for @chatroom, html: { class: "nobottommargin" } do |f|
            %h3 Create a New Chatroom
            .col_two_third
              %label Name
              = f.input :name, label: false,
                input_html: { class: "form-control", placeholder: "Name" }
            .col_one_third.col_last
              %label Private?
              = f.input :private_channel, as: :boolean, label: false
            .col_full
              %label Invite Your Friends!
              = f.input :user_ids, collection: @users, label: false,
                input_html: { class: "form-control", multiple: true }
            .col_full.nobottommargin
              = f.submit class: "button button-3d button-black nomargin"
:javascript
  $(document).on("turbolinks:load", function() {
    $("#chatroom_user_ids").select2({
    placeholder: "Invite Users"
    });

    $('#chatroom_private_channel').bootstrapSwitch({
      onText:  "Yes",
      offText: "No"
    });
  });

app/views/chatrooms/show.html.haml
%section#content
  .container.clearfix
    .heading-block.center.nobottomborder.topmargin
      %h1= @chatroom.name

  .content-wrap
    .nobottommargin.clearfix
      #chatroom.messages.list-group{"data-chatroom-id" => @chatroom.id}
        - @messages.each do |message|
          - if !@unread_messages && @chatroom_membership.last_read_at < message.created_at
            - @unread_messages = true
            .divider.divider-short.divider-center
              %i.icon-crop
          = render partial: message, locals: { message_user: message.user }


%footer#footer{style: "z-index: 100000"}
  = simple_form_for [@chatroom, @message] do |f|
    = f.input :body, input_html: { class: 'form-control nobottommargin' },
      label: false, as: :string,
      placeholder: 'Type & Hit Enter...', autofocus: true

:javascript
  $(document).on("turbolinks:load", function() {
    new Chatrooms.Views.Chatroom
    window.scrollTo(0,document.body.scrollHeight);
  });

app/views/layouts/_header.html.haml
%header#header.full-header{"data-sticky-class" => "not-dark"}
  #header-wrap
    .container.clearfix
      #primary-menu-trigger
        %i.icon-reorder
      #logo
        = link_to chatrooms_path, class: "retina-logo standard-logo" do
          = image_tag "logo.jpg"

      %nav#primary-menu.dark
        %ul
          %li
            = link_to "Signed In as #{current_user.name}", "javascript:void(0)",
              id: "signed-in-as", data: { :"current-user-id" => current_user.id }

          %li
            - if user_signed_in?
              = link_to "Sign Out", destroy_user_session_path, method: :delete
            - else
              = link_to "Sign In", new_user_session_path
        #side-panel-trigger.side-panel-trigger
          %a{:href => "#"}
            %i.icon-line-layout

app/views/layouts/_side_panel.html.haml
.body-overlay
#side-panel
  #side-panel-trigger-close.side-panel-trigger
    = link_to "javascript:void(0)" do
      %i.icon-line-cross
  .side-panel-wrap
    .widget.clearfix
      - if user_signed_in?
        %h4 Your Chatrooms
        %nav#current-chatrooms.nav-tree.nobottommargin
          %ul
            - current_user.chatrooms.each do |chatroom|
              %li{id: "chatroom_link_#{chatroom.id}"}
                = link_to chatroom_path(chatroom) do
                  = truncate(chatroom.name, length: 17)
                  %i.icon-circle{style: "display: none; color: #00CDCD"}

        .divider
          %i.icon-circle

        - if current_user.invited_chatrooms.any?
          %h4 Invitations
          %nav#chatroom-invites.nav-tree.nobottommargin
            %ul
              - current_user.invited_chatrooms.each do |chatroom|
                %li
                  = link_to "javascript:void(0)" do
                    = truncate(chatroom.name, length: 17)
                  = link_to accept_chatroom_chatroom_memberships_path(chatroom), method: :post do
                    %i.icon-line-plus
                  = link_to chatroom_chatroom_memberships_path(chatroom), method: :delete do
                    %i.icon-line-cross

          .divider
            %i.icon-circle

        %h4 Settings
        %nav#settings.nav-tree.nobottommargin
          %ul
            %li
              = link_to "Get Notifications", "#notifications-modal", 
                data: { lightbox: "inline" }
      - else
        %h4 Sign in to join chatrooms

#notifications-modal.modal1.mfp-hide
  .block.divcenter{style: "background-color: #FFF; max-width: 500px;"}
    .center{style: "padding: 50px;"}
      %h3 Enable Browswer Notifications Here!
      %p.nobottommargin
        Enable browser notifications to be notified whenever someone in your
        chatroom sends a message while you're browsing on another tab!
    .section.center.nomargin{:style => "padding: 30px;"}
      = link_to "Get Notifications", "#", id: "notifications-trigger",
        class: "button"
      = link_to "Close", "#", id: "close-notifications-modal", class: "button"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chatrooms
    = favicon_link_tag
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.no-transition.stretched.side-panel-left.sticky-footer
    - if user_signed_in?
      = render partial: "layouts/side_panel"
      = render partial: "layouts/header"
    #wrapper.clearfix
      = yield
    #gotoTop.icon-angle-up.bottommargin
  = javascript_include_tag 'functions.js', 'data-turbolinks-track': 'reload'

app/views/messages/_message.html.haml
- if message_user == current_user
  .col_one_third
  .col_two_third.col_last
    .message.your_message
      .username= message.user.name

      .body= message.body
      .details= message.created_at.strftime('%l:%M %p')
- else
  .col_two_third
    .message.someone_elses_message
      .username= message.user.name

      .body= message.body
      .details= message.created_at.strftime('%l:%M %p')